public:
  AccountId:
  AccountNumber: string
  Errors: Error[]
  InvoiceId:
  InvoiceNumber: string
  PaymentTransactionNumber: string
  SubscriptionId:
  SubscriptionNumber: string
  Success: boolean